platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 14 x64
  - npm install

build_script:
  - npm run dist

test: off

branches:
  only:
    - main
    
environment:
  GH_TOKEN:
    secure: wKpcP/4h8crN/wgqTxp35BBv9c0dLrX3z4et9a2W3znxImFFM9s2wy58tkrn5QTh